<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>TriviaDotNetApi.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="IntegrationEvents\Events\" />
    <Folder Include="IntegrationEvents\Handlers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.0" />
    <PackageReference Include="Saunter" Version="0.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrossCutting\CrossCutting.csproj" />
    <ProjectReference Include="..\TriviaDotNetApi.Infrastructure\TriviaDotNetApi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
