FROM mcr.microsoft.com/dotnet/core/sdk:3.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY [".Personnel.API/.Personnel.API.csproj", ".Personnel.API/"]
COPY [".Personnel.Application/.Personnel.Application.csproj", ".Personnel.Application/"]
COPY [".Personnel.Domain/.Personnel.Domain.csproj", ".Personnel.Domain/"]
COPY [".Personnel.Infrastructure/.Personnel.Infrastructure.csproj", ".Personnel.Infrastructure/"]

RUN dotnet restore ".Personnel.API/.Personnel.API.csproj"
COPY . .
WORKDIR "/src/.Personnel.API"
RUN dotnet build --no-restore ".Personnel.API.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]